project:
  type: website
  output-dir: docs

website:
  title: "Urban Creative Commons"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: The Datasets
      - href: game.qmd
        text: The Game
    tools:
      - icon: github
        href: https://github.com/sokimura39/urban_cc

format:
  html:
    theme: lumen
    toc: false

